version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./core:/app/core
      - ./.env:/app/.env:ro
    command: bash -lc "pip install -r core/requirements.txt && uvicorn core.app.main:app --host 0.0.0.0 --port 8769"
    ports:
      - "8769:8769"

  ui:
    image: node:20
    working_dir: /app
    volumes:
      - ./ui:/app/ui
    command: bash -lc "cd ui && npm ci || npm install && npm run dev"
    ports:
      - "5174:5174"

  # Uncomment if you want Neo4j in dev; otherwise keep off by default
  # neo4j:
  #   image: neo4j:5
  #   environment:
  #     - NEO4J_AUTH=neo4j/password
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - ./core/kg/neo4j_data:/data
  #     - ./core/kg/neo4j_logs:/logs
